### ISSUE TITLE
Latex renders only on first page load on Nuxt.js SPA. Fails to re-render when navigating back and forward.

### ISSUE THREAD

**Issue by imricardoramos** [pyramation/LaTeX2HTML5#3]
Hi, I'm using Nuxt.js and I've followed the [instructions](https://latex2js.com/installation/vue.html). 

Everything seems to work fine when hard-reloading the page where I have the `<latex>` tags. However, when I navigate the website and go to another page and then back (using `<nuxt-link>`s), the latex is not rendered and doesn't re-render either.

Is there any way to fix this or force the re-render?

Thanks.

**Comment by imricardoramos** [comment]
Okay, so I actually made a partial solution using [this](https://github.com/GitbookIO/plugin-mathjax/issues/34) as a reference.
I edited the latex.vue in the node_modules/latex2vue/:
```
mounted(){
    let MathJax = getMathJax()
    if(MathJax != undefined)
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
},
```
And I also edited the beforeMount() part:
```
if (getMathJax()) {
    this.loaded = true
    return;
}
```

**Comment by pyramation** [comment]
thank you! 

Do you have a solution suggestion that would make this work more generally?

**Comment by imricardoramos** [comment]
The workaround I mentioned was good enough for me (for now) so I stopped searching for a better one 🤷‍♂️.

**Comment by pyramation** [comment]
looks like this may solve the issue https://github.com/pyramation/LaTeX2JS/pull/10/commits/e16e67066de9b37f68df90561601168814ac7801

**Comment by pyramation** [comment]
should close with https://github.com/pyramation/LaTeX2JS/pull/19
